Prepare repository for opensourcing (#16)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,19 +13,6 @@ on:
         description: "Profiler version to use for the build"
         
 jobs:
-  copyright:
-    runs-on: ubuntu-24.04
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Setup go
-        uses: actions/setup-go@v5
-        with:
-          go-version: ${{ inputs.go-version }}
-      - name: Copyright
-        run: |
-          go run checkcopyright.go
-
   lint:
     name: Lint
     runs-on: ubuntu-24.04
@@ -42,6 +29,30 @@ jobs:
         golangci_lint_version: ${{ steps.linter-version.outputs.version }}
         fail_on_error: true
         reporter: github-pr-review
+    - name: Verify copyright headers
+      run: |
+        go run tools/checkcopyright.go
+    - name: vet
+      run: go vet ./...
+    - name: Run 'go mod tidy'
+      run: find . -iname go.mod -execdir go mod tidy \;
+    - name: Refresh LICENSE-3rdparty.csv
+      run: make licenses
+      env:
+        TMPDIR: ${{ runner.temp }}
+    - name: Check if working tree is dirty
+      id: is-tree-dirty
+      run: |-
+        set -euxo pipefail
+        git add .
+        git status
+        git diff --staged --patch --exit-code > .repo.patch || echo 'result=true' >> "${GITHUB_OUTPUT}"
+    - name: Fail build if working tree is dirty
+      if: steps.is-tree-dirty.outputs.result == 'true'
+      run: |-
+        echo "::error::Files have been modified by 'go mod tidy' or 'make licenses' (see logs)."
+        cat .repo.patch
+        exit 1
 
   test:
     name: Test
